Update c-compilers.yml

diff --git a/.github/workflows/c-compilers.yml b/.github/workflows/c-compilers.yml
--- a/.github/workflows/c-compilers.yml
+++ b/.github/workflows/c-compilers.yml
@@ -42,21 +42,21 @@ jobs:
 ####          #{pkgs: 'gcc-4.5 g++-4.5',                                    cc: gcc-4.5,   cxx: g++-4.5,     stdc11: 'false', stdc90: 'true',  x32: 'false', x86: 'success',   os: ubuntu-16.04,  },  # Failed to install gcc-4.5.  Dependent package is not installable.
 ####          { pkgs: 'gcc-4.4 g++-4.4 gcc-4.4-multilib',                   cc: gcc-4.4,   cxx: g++-4.4,     stdc11: 'false', stdc90: 'false', x32: 'false', x86: 'success',   os: ubuntu-16.04,  },  # gcc-4.4 doesn't support C90 https://gcc.gnu.org/onlinedocs/gcc-4.4.7/gcc/C-Dialect-Options.html#C-Dialect-Options
 
-          # clang
-          { pkgs: 'clang-12  lib32gcc-11-dev libx32gcc-11-dev',         cc: clang-12,  cxx: clang++-12,  stdc11: 'true',  stdc90: 'true',  x32: 'fail',  x86: 'fail',    os: ubuntu-20.04,  }, # MOREFLAGS='-mx32 -Wl,--verbose' make V=1 -C tests clean test, lz4: ../lib/lz4hc.c:282: int LZ4HC_InsertAndGetWiderMatch(...), Assertion `matchPtr >= lowPrefixPtr' failed.
-          { pkgs: 'clang-11  lib32gcc-11-dev libx32gcc-11-dev',         cc: clang-11,  cxx: clang++-11,  stdc11: 'true',  stdc90: 'true',  x32: 'fail',  x86: 'fail',    os: ubuntu-20.04,  }, # MOREFLAGS='-mx32 -Wl,--verbose' make V=1 -C tests clean test, lz4: ../lib/lz4hc.c:282: int LZ4HC_InsertAndGetWiderMatch(...), Assertion `matchPtr >= lowPrefixPtr' failed.
-          { pkgs: 'clang-10  lib32gcc-11-dev libx32gcc-11-dev',         cc: clang-10,  cxx: clang++-10,  stdc11: 'true',  stdc90: 'true',  x32: 'fail',  x86: 'fail',    os: ubuntu-20.04,  },
-          { pkgs: 'clang-9   lib32gcc-11-dev libx32gcc-11-dev',         cc: clang-9,   cxx: clang++-9,   stdc11: 'true',  stdc90: 'true',  x32: 'fail',  x86: 'fail',    os: ubuntu-20.04,  },
-          { pkgs: 'clang-8   lib32gcc-11-dev libx32gcc-11-dev',         cc: clang-8,   cxx: clang++-8,   stdc11: 'true',  stdc90: 'true',  x32: 'fail',  x86: 'fail',    os: ubuntu-20.04,  },
-          { pkgs: 'clang-7   lib32gcc-7-dev  libx32gcc-7-dev',          cc: clang-7,   cxx: clang++-7,   stdc11: 'true',  stdc90: 'true',  x32: 'fail',  x86: 'fail',    os: ubuntu-20.04,  },
-          { pkgs: 'clang-6.0 lib32gcc-11-dev libx32gcc-11-dev',         cc: clang-6.0, cxx: clang++-6.0, stdc11: 'true',  stdc90: 'true',  x32: 'fail',  x86: 'fail',    os: ubuntu-20.04,  }, # MOREFLAGS='-mx32 -Wl,--verbose' make V=1 -C tests clean test, lz4: ../lib/lz4hc.c:282: int LZ4HC_InsertAndGetWiderMatch(...), Assertion `matchPtr >= lowPrefixPtr' failed.
-          { pkgs: 'clang-5.0 lib32gcc-11-dev libx32gcc-11-dev',         cc: clang-5.0, cxx: clang++-5.0, stdc11: 'true',  stdc90: 'true',  x32: 'fail',  x86: 'fail',    os: ubuntu-18.04,  }, # MOREFLAGS='-mx32 -Wl,--verbose' make V=1 -C tests clean test, lz4: ../lib/lz4hc.c:282: int LZ4HC_InsertAndGetWiderMatch(...), Assertion `matchPtr >= lowPrefixPtr' failed.
-          { pkgs: 'clang-4.0 lib32gcc-11-dev libx32gcc-11-dev',         cc: clang-4.0, cxx: clang++-4.0, stdc11: 'true',  stdc90: 'true',  x32: 'fail',  x86: 'fail',    os: ubuntu-18.04,  }, # MOREFLAGS='-mx32 -Wl,--verbose' make V=1 -C tests clean test, lz4: ../lib/lz4hc.c:282: int LZ4HC_InsertAndGetWiderMatch(...), Assertion `matchPtr >= lowPrefixPtr' failed.
-          { pkgs: 'clang-3.9 lib32gcc-11-dev libx32gcc-11-dev',         cc: clang-3.9, cxx: clang++-3.9, stdc11: 'true',  stdc90: 'true',  x32: 'fail',  x86: 'fail',    os: ubuntu-18.04,  }, # MOREFLAGS='-mx32 -Wl,--verbose' make V=1 -C tests clean test, ../programs/lz4 -bi0 -> make: *** [test-lz4-testmode] Segmentation fault (core dumped
-          { pkgs: 'clang-3.8',                                          cc: clang-3.8, cxx: clang++-3.8, stdc11: 'true',  stdc90: 'true',  x32: 'fail',  x86: 'fail',    os: ubuntu-16.04,  }, # MOREFLAGS='-mx32 -Wl,--verbose' make V=1 -C tests clean test, lz4: ../lib/lz4hc.c:282: int LZ4HC_InsertAndGetWiderMatch(...), Assertion `matchPtr >= lowPrefixPtr' failed.
-          { pkgs: 'clang-3.7',                                          cc: clang-3.7, cxx: clang++-3.7, stdc11: 'true',  stdc90: 'true',  x32: 'false', x86: 'fail',    os: ubuntu-16.04,  }, # clang-3.7 compiler clashes for x32, LDFLAGS='-Wl,--verbose' MOREFLAGS='-Werror' make V=1 -C tests clean test-lz4c32 , lz4: ../lib/lz4hc.c:282: int LZ4HC_InsertAndGetWiderMatch(...), Assertion `matchPtr >= lowPrefixPtr' failed.
-          { pkgs: 'clang-3.6',                                          cc: clang-3.6, cxx: clang++-3.6, stdc11: 'true',  stdc90: 'true',  x32: 'false', x86: 'fail',    os: ubuntu-16.04,  }, # clang-3.6 compiler clashes for x32, LDFLAGS='-Wl,--verbose' MOREFLAGS='-Werror' make V=1 -C tests clean test-lz4c32 , lz4: ../lib/lz4hc.c:282: int LZ4HC_InsertAndGetWiderMatch(...), Assertion `matchPtr >= lowPrefixPtr' failed.
-          { pkgs: 'clang-3.5',                                          cc: clang-3.5, cxx: clang++-3.5, stdc11: 'true',  stdc90: 'true',  x32: 'false', x86: 'fail',    os: ubuntu-16.04,  }, # clang-3.5 compiler clashes for x32, LDFLAGS='-Wl,--verbose' MOREFLAGS='-Werror' make V=1 -C tests clean test-lz4c32 , lz4: ../lib/lz4hc.c:282: int LZ4HC_InsertAndGetWiderMatch(...), Assertion `matchPtr >= lowPrefixPtr' failed.
+####          # clang
+####          { pkgs: 'clang-12  lib32gcc-11-dev libx32gcc-11-dev',         cc: clang-12,  cxx: clang++-12,  stdc11: 'true',  stdc90: 'true',  x32: 'fail',  x86: 'fail',    os: ubuntu-20.04,  }, # MOREFLAGS='-mx32 -Wl,--verbose' make V=1 -C tests clean test, lz4: ../lib/lz4hc.c:282: int LZ4HC_InsertAndGetWiderMatch(...), Assertion `matchPtr >= lowPrefixPtr' failed.
+####          { pkgs: 'clang-11  lib32gcc-11-dev libx32gcc-11-dev',         cc: clang-11,  cxx: clang++-11,  stdc11: 'true',  stdc90: 'true',  x32: 'fail',  x86: 'fail',    os: ubuntu-20.04,  }, # MOREFLAGS='-mx32 -Wl,--verbose' make V=1 -C tests clean test, lz4: ../lib/lz4hc.c:282: int LZ4HC_InsertAndGetWiderMatch(...), Assertion `matchPtr >= lowPrefixPtr' failed.
+####          { pkgs: 'clang-10  lib32gcc-11-dev libx32gcc-11-dev',         cc: clang-10,  cxx: clang++-10,  stdc11: 'true',  stdc90: 'true',  x32: 'fail',  x86: 'fail',    os: ubuntu-20.04,  },
+####          { pkgs: 'clang-9   lib32gcc-11-dev libx32gcc-11-dev',         cc: clang-9,   cxx: clang++-9,   stdc11: 'true',  stdc90: 'true',  x32: 'fail',  x86: 'fail',    os: ubuntu-20.04,  },
+####          { pkgs: 'clang-8   lib32gcc-11-dev libx32gcc-11-dev',         cc: clang-8,   cxx: clang++-8,   stdc11: 'true',  stdc90: 'true',  x32: 'fail',  x86: 'fail',    os: ubuntu-20.04,  },
+####          { pkgs: 'clang-7   lib32gcc-7-dev  libx32gcc-7-dev',          cc: clang-7,   cxx: clang++-7,   stdc11: 'true',  stdc90: 'true',  x32: 'fail',  x86: 'fail',    os: ubuntu-20.04,  },
+####          { pkgs: 'clang-6.0 lib32gcc-11-dev libx32gcc-11-dev',         cc: clang-6.0, cxx: clang++-6.0, stdc11: 'true',  stdc90: 'true',  x32: 'fail',  x86: 'fail',    os: ubuntu-20.04,  }, # MOREFLAGS='-mx32 -Wl,--verbose' make V=1 -C tests clean test, lz4: ../lib/lz4hc.c:282: int LZ4HC_InsertAndGetWiderMatch(...), Assertion `matchPtr >= lowPrefixPtr' failed.
+####          { pkgs: 'clang-5.0 lib32gcc-11-dev libx32gcc-11-dev',         cc: clang-5.0, cxx: clang++-5.0, stdc11: 'true',  stdc90: 'true',  x32: 'fail',  x86: 'fail',    os: ubuntu-18.04,  }, # MOREFLAGS='-mx32 -Wl,--verbose' make V=1 -C tests clean test, lz4: ../lib/lz4hc.c:282: int LZ4HC_InsertAndGetWiderMatch(...), Assertion `matchPtr >= lowPrefixPtr' failed.
+####          { pkgs: 'clang-4.0 lib32gcc-11-dev libx32gcc-11-dev',         cc: clang-4.0, cxx: clang++-4.0, stdc11: 'true',  stdc90: 'true',  x32: 'fail',  x86: 'fail',    os: ubuntu-18.04,  }, # MOREFLAGS='-mx32 -Wl,--verbose' make V=1 -C tests clean test, lz4: ../lib/lz4hc.c:282: int LZ4HC_InsertAndGetWiderMatch(...), Assertion `matchPtr >= lowPrefixPtr' failed.
+####          { pkgs: 'clang-3.9 lib32gcc-11-dev libx32gcc-11-dev',         cc: clang-3.9, cxx: clang++-3.9, stdc11: 'true',  stdc90: 'true',  x32: 'fail',  x86: 'fail',    os: ubuntu-18.04,  }, # MOREFLAGS='-mx32 -Wl,--verbose' make V=1 -C tests clean test, ../programs/lz4 -bi0 -> make: *** [test-lz4-testmode] Segmentation fault (core dumped
+####          { pkgs: 'clang-3.8',                                          cc: clang-3.8, cxx: clang++-3.8, stdc11: 'true',  stdc90: 'true',  x32: 'fail',  x86: 'fail',    os: ubuntu-16.04,  }, # MOREFLAGS='-mx32 -Wl,--verbose' make V=1 -C tests clean test, lz4: ../lib/lz4hc.c:282: int LZ4HC_InsertAndGetWiderMatch(...), Assertion `matchPtr >= lowPrefixPtr' failed.
+####          { pkgs: 'clang-3.7',                                          cc: clang-3.7, cxx: clang++-3.7, stdc11: 'true',  stdc90: 'true',  x32: 'false', x86: 'fail',    os: ubuntu-16.04,  }, # clang-3.7 compiler clashes for x32, LDFLAGS='-Wl,--verbose' MOREFLAGS='-Werror' make V=1 -C tests clean test-lz4c32 , lz4: ../lib/lz4hc.c:282: int LZ4HC_InsertAndGetWiderMatch(...), Assertion `matchPtr >= lowPrefixPtr' failed.
+####          { pkgs: 'clang-3.6',                                          cc: clang-3.6, cxx: clang++-3.6, stdc11: 'true',  stdc90: 'true',  x32: 'false', x86: 'fail',    os: ubuntu-16.04,  }, # clang-3.6 compiler clashes for x32, LDFLAGS='-Wl,--verbose' MOREFLAGS='-Werror' make V=1 -C tests clean test-lz4c32 , lz4: ../lib/lz4hc.c:282: int LZ4HC_InsertAndGetWiderMatch(...), Assertion `matchPtr >= lowPrefixPtr' failed.
+####          { pkgs: 'clang-3.5',                                          cc: clang-3.5, cxx: clang++-3.5, stdc11: 'true',  stdc90: 'true',  x32: 'false', x86: 'fail',    os: ubuntu-16.04,  }, # clang-3.5 compiler clashes for x32, LDFLAGS='-Wl,--verbose' MOREFLAGS='-Werror' make V=1 -C tests clean test-lz4c32 , lz4: ../lib/lz4hc.c:282: int LZ4HC_InsertAndGetWiderMatch(...), Assertion `matchPtr >= lowPrefixPtr' failed.
         ]
 
     runs-on: ${{ matrix.os }}
@@ -66,10 +66,6 @@ jobs:
       CXX: ${{ matrix.cxx }}
     steps:
     - uses: actions/checkout@v2 # https://github.com/actions/checkout
-    - name: apt-get remove
-      if: ${{ matrix.pkgremove != '' }}
-      run: |
-        sudo apt-get remove ${{ matrix.pkgremove }}
 
     - name: apt-get install
       run: |
@@ -86,6 +82,12 @@ jobs:
 ####    - name: make
 ####      run: |
 ####        make V=1
+
+    - name: make failure test
+      run: |
+        ! make V=1 || (echo SUCCESS!!  But set RED to suggest to update the test case && $(exit 1))
+        echo We ignore failure of this case for now.
+
 ####
 ####    - name: make all
 ####      run: |
@@ -134,7 +136,8 @@ jobs:
     - name: make -C tests test MOREFLAGS='-mx32' || echo Ignore failure for now.
       if: ${{ matrix.x32 == 'fail' }}
       run: |
-        LDFLAGS='-Wl,--verbose' MOREFLAGS='-mx32' make V=1 -C tests clean test || (echo Ignore FAIL for now. && $(exit 0))
+        ! LDFLAGS='-Wl,--verbose' MOREFLAGS='-mx32' make V=1 -C tests clean test && (echo SUCCESS!! but set RED to suggest to update the test case && $(exit 1))
+        echo We ignore failure of this case for now.
 
     - name: make -C tests test-lz4c32
       if: ${{ matrix.x86 != 'fail' }}
@@ -144,4 +147,5 @@ jobs:
     - name: make -C tests test-lz4c32 || echo Ignore failure for now.
       if: ${{ matrix.x86 == 'fail' }}
       run: |
-        LDFLAGS='-Wl,--verbose' MOREFLAGS='-Werror' make V=1 -C tests clean test-lz4c32 || (echo Ignore FAIL for now. && $(exit 0))
+        ! LDFLAGS='-Wl,--verbose' MOREFLAGS='-Werror' make V=1 -C tests clean test-lz4c32 || (echo SUCCESS!!  But set RED to suggest to update the test case && $(exit 1))
+        echo We ignore failure of this case for now.
