Update ubsan.yml

diff --git a/.github/workflows/ubsan.yml b/.github/workflows/ubsan.yml
--- a/.github/workflows/ubsan.yml
+++ b/.github/workflows/ubsan.yml
@@ -1,13 +1,24 @@
-####name: ubsan
-####on: [push, pull_request]
-####jobs:
-####  lz4-ubsan:
-####    name: Linux x64 ubsan, ubsan.yml
-####    runs-on: ubuntu-latest
-####    steps:
-####    - uses: actions/checkout@v2 # https://github.com/actions/checkout
-####    - name: ubsan
-####      # For now, we ignore the exit code of `make usan`.
-####      # See "Known issues" in README.md
-####      run: |
-####        make V=1 clean usan MOREFLAGS='-Wcomma -Werror' || echo Ignore these errors for now.  For details, see https://github.com/lz4/lz4/pull/983
+name: ubsan
+on: [push, pull_request]
+jobs:
+  lz4-ubsan:
+    name: Linux x64 ubsan, ubsan.yml
+    runs-on: ubuntu-latest
+    steps:
+    - uses: actions/checkout@v2 # https://github.com/actions/checkout
+    - name: ubsan
+      # For now, we ignore the exit code of `make usan`.
+      # See "Known issues" in README.md
+      run: |
+        make V=1 clean usan MOREFLAGS='-Wcomma -Werror' || echo Ignore these errors for now.  For details, see https://github.com/lz4/lz4/pull/983
+
+  lz4-ubsan-32:
+    name: Linux x86 ubsan, ubsan.yml
+    runs-on: ubuntu-latest
+    steps:
+    - uses: actions/checkout@v2 # https://github.com/actions/checkout
+    - name: ubsan
+      # For now, we ignore the exit code of `make usan`.
+      # See "Known issues" in README.md
+      run: |
+        make V=1 clean usan32 MOREFLAGS='-Wcomma -Werror' || echo Ignore these errors for now.  For details, see https://github.com/lz4/lz4/pull/983
